### PR TITLE
Update api scheme to latest smsmisr. and update to Laravel/PHP 8

### PR DESCRIPTION
**Pull request by Saifallak**
## Changes 👍 
- Updated API Scheme to latest sms misr one here: https://smsmisr.com/Api_SMSMisr.pdf and here
 image
- Updated depends to allow laravel 8 and PHP 8
- added config vars
- - m_signature => needed in verify endpoint
- - token => needed in verify endpoint
- - sms_id => in balance endpoint, why this was fixed?
- - sms_verify_id => in balance endpoint why this was fixed
- updated docs and added isSuccessful method

### CODE REVIEW

**Comment by AbdullahGhanem** [comment]
thanks saif

**Comment by Saifallak** [comment]
> thanks saif

welcome, also thanks for the great package.

**Comment by Saifallak** [comment]
after checking out my commits, looks like i forgot to update readme.md to reflect php +8 and laravel +8 only.

can you metion it ? @AbdullahGhanem

**Comment by AbdullahGhanem** [comment]
[SHA-53388c7ce35ba4ffb5d0405f997a8ac44eeb91cf 
](https://github.com/AbdullahGhanem/laravel-smsmisr/commit/53388c7ce35ba4ffb5d0405f997a8ac44eeb91cf)
ok, done @Saifallak

**Pull request merged**
